"""removed datatime now id datatype changed to string

Revision ID: 0c28ae7037fd
Revises: e4fbb6e27a2e
Create Date: 2025-09-18 08:32:47.819021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c28ae7037fd'
down_revision: Union[str, Sequence[str], None] = 'e4fbb6e27a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    print('ssssssssssssssssssssssssssssssssssssssssssssssss-----------------------------------------------------')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
