"""updated datatype to intger return

Revision ID: 3ad024064405
Revises: cc9b824dee05
Create Date: 2025-09-18 11:12:11.038984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad024064405'
down_revision: Union[str, Sequence[str], None] = 'cc9b824dee05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_master',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.company_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_master.user_id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_master')
    # ### end Alembic commands ###
