"""datatype changedg

Revision ID: 3ba40bf3dd1e
Revises: 0c28ae7037fd
Create Date: 2025-09-18 08:34:17.244776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba40bf3dd1e'
down_revision: Union[str, Sequence[str], None] = '0c28ae7037fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table("instance")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance', 'instance_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('instance_instance_id_seq'::regclass)"))
    # ### end Alembic commands ###
