"""datatype changed to string

Revision ID: 68318a8d4fbe
Revises: 6473f5f1ef7a
Create Date: 2025-09-18 11:02:40.538952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68318a8d4fbe'
down_revision: Union[str, Sequence[str], None] = '6473f5f1ef7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_master', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_master', 'status',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
