"""updated instance tabler

Revision ID: 6c4cc0985de5
Revises: c72f6fa2c6e6
Create Date: 2025-09-17 22:07:16.871277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4cc0985de5'
down_revision: Union[str, Sequence[str], None] = 'c72f6fa2c6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'instance', 'user_master', ['created_by'], ['user_id'])
    op.drop_column('instance', 'modified_by')
    op.drop_column('instance', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('modified_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instance', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'instance', type_='foreignkey')
    # ### end Alembic commands ###
