"""added few things

Revision ID: 880d70d7b108
Revises: a375ae1b38a5
Create Date: 2025-09-17 21:59:42.017334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880d70d7b108'
down_revision: Union[str, Sequence[str], None] = 'a375ae1b38a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_master', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_master', 'is_active')
    # ### end Alembic commands ###
