"""set foreign key for instances with company 

Revision ID: 8a0fe6c0c069
Revises: c39854c1679d
Create Date: 2025-09-17 19:00:31.414835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0fe6c0c069'
down_revision: Union[str, Sequence[str], None] = 'c39854c1679d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instance', 'company_master', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instance', type_='foreignkey')
    op.drop_column('instance', 'company_id')
    # ### end Alembic commands ###
