"""role and user table created

Revision ID: 94f603d77096
Revises: 7d9f81700ed3
Create Date: 2025-09-17 13:03:13.229924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f603d77096'
down_revision: Union[str, Sequence[str], None] = '7d9f81700ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_master',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.String(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.add_column('user_master', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_master', 'role_master', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_master', type_='foreignkey')
    op.drop_column('user_master', 'role_id')
    op.drop_table('role_master')
    # ### end Alembic commands ###
