"""user and company table updated"

Revision ID: a375ae1b38a5
Revises: 8a0fe6c0c069
Create Date: 2025-09-17 21:52:45.398967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a375ae1b38a5'
down_revision: Union[str, Sequence[str], None] = '8a0fe6c0c069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('company_master_modified_by_fkey'), 'company_master', type_='foreignkey')
    op.drop_column('company_master', 'modified_by')
    op.drop_column('company_master', 'modified_at')

    op.add_column('user_master', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_master', 'created_at')
    op.drop_column('user_master', 'is_active')
    op.add_column('company_master', sa.Column('modified_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company_master', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('company_master_modified_by_fkey'), 'company_master', 'user_master', ['modified_by'], ['user_id'])
    # ### end Alembic commands ###
