"""instance table created include foreign key

Revision ID: c39854c1679d
Revises: dca08718b29a
Create Date: 2025-09-17 17:45:11.431357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39854c1679d'
down_revision: Union[str, Sequence[str], None] = 'dca08718b29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.String(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('instance_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_master',
    sa.Column('company_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_master.user_id'], name=op.f('company_master_created_by_fkey')),
    sa.ForeignKeyConstraint(['modified_by'], ['user_master.user_id'], name=op.f('company_master_modified_by_fkey')),
    sa.PrimaryKeyConstraint('company_id', name=op.f('company_master_pkey'))
    )
    op.drop_table('instance')
    # ### end Alembic commands ###
