"""updated datatype to intger return

Revision ID: cc9b824dee05
Revises: 68318a8d4fbe
Create Date: 2025-09-18 11:07:06.177160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9b824dee05'
down_revision: Union[str, Sequence[str], None] = '68318a8d4fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table('instance_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_master', 'instance_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('instance_master_instance_id_seq'::regclass)"))
    # ### end Alembic commands ###
