"""extra column user_role removed

Revision ID: d4a8d388c76a
Revises: 94f603d77096
Create Date: 2025-09-17 13:58:59.291197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a8d388c76a'
down_revision: Union[str, Sequence[str], None] = '94f603d77096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_master', 'user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_master', sa.Column('user_role', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
